# Example/Documentation for the IG YML file
# https://fshschool.org/docs/sushi/configuration/#exhaustive-example

# Package name
# https://confluence.hl7.org/display/FHIR/NPM+Package+Specification#NPMPackageSpecification-Packagename
id: ch.fhir.ig.ch-idmp
canonical: http://fhir.ch/ig/ch-idmp
url: http://fhir.ch/ig/ch-idmp/ImplementationGuide/ch.fhir.ig.ch-idmp
name: CH_IDMP
title: "CH IDMP (R5)"
description: Implementation Guide CH IDMP (R5)
status: draft
license: CC0-1.0
copyright: CC0-1.0
jurisdiction: urn:iso:std:iso:3166#CH
date: 2026-06-22
version: 1.0.0-ballot
fhirVersion: 5.0.0
copyrightYear: 2026+
releaseLabel: ballot # ci-build | draft | qa-preview | ballot | trial-use | release | update | normative+trial-use
publisher:
  name: Refdata Foundation
contact:
  - name: Refdata Foundation
    telecom:
      - system: url
        value: https://www.refdata.ch/de/

dependencies:
  hl7.terminology.r5:
    uri: http://terminology.hl7.org/ImplementationGuide/hl7.terminology
    version: 7.1.0
  hl7.fhir.uv.tools.r5:
    uri: http://hl7.org/fhir/tools/ImplementationGuide/hl7.fhir.uv.tools
    version: 1.1.2

pages:
  index.md:
    title: Home
  fhir.md:
    title: FHIR Standard HL7
  project.md:
    title: Project Description
  idmp.md:
    title: ISO IDMP Standard (ISO 11615)
  fhir-idmp.md:
    title: IDMP and FHIR
  ch-idmp.md:
    title: Swiss IDMP Implementation
  ema-idmp.md:
    title: EMA IDMP Implementation and SPOR Overview
  smc-idmp.md:
    title: Swissmedic IDMP Implementation
  comprehensive.md:
    title: Comprehensive
  padcev20.md:
    title: Padcev20
  padcev30.md:
    title: Padcev30
  xospata.md:
    title: Xospata
  profiles.md:
    title: Profiles
  extensions.md:
    title: Extensions
  terminology.md:
    title: Terminology
  changelog.md:
    title: Changelog

menu:
  Home: index.html
  Documentation:
    Project Description: project.html
    Swiss IDMP Implementation: ch-idmp.html
    Swissmedic IDMP Implementation: smc-idmp.html
    EMA IDMP Implementation: ema-idmp.html
  Related Standards:
    HL7 FHIR Standard: fhir.html
    ISO IDMP Standard (ISO 11615): idmp.html
    IDMP and FHIR: fhir-idmp.html
  Examples: 
     Comprehensive: comprehensive.html
     Padcev 20 mg: padcev20.html
     Padcev 30 mg: padcev30.html
     Xospata: xospata.html
  Profiles: profiles.html
  Extensions: extensions.html
  Terminology: terminology.html
  Artifacts: artifacts.html

# Core FHIR: http://build.fhir.org/codesystem-guide-parameter-code.html
# FHIR Tools IG: http://build.fhir.org/ig/FHIR/fhir-tools-ig/branches/master/CodeSystem-ig-parameters.html
parameters:
  excludettl: true
  allow-extensible-warnings: true
  display-warnings: true
  path-expansion-params: '../../expansion-params.json' # for using SNOMED CT Swiss Extension
  special-url:
    - urn:oid:0.4.0.127.0.16.1.1.2.1 # edqm-standard-terms
    - urn:oid:0.4.0.127.0.16.1.1.2.2 # edqm-pharmaceutical-dose-form
    - urn:oid:0.4.0.127.0.16.1.1.2.3 # edqm-combined-pharmaceutical-dose-form
    - urn:oid:0.4.0.127.0.16.1.1.2.4 # edqm-combined-term
    - urn:oid:0.4.0.127.0.16.1.1.2.5 # edqm-combination-packaging
    - urn:oid:0.4.0.127.0.16.1.1.2.6 # edqm-route-of-administration
    - urn:oid:0.4.0.127.0.16.1.1.2.7 # edqm-packaging
    - urn:oid:0.4.0.127.0.16.1.1.2.11 # edqm-unit-of-presentation
    - http://standardterms.edqm.eu # edqm
    - https://spor.ema.europa.eu/v1/lists # ema-rms
    - http://spor.ema.europa.eu/v1/lists/100000000004 # ema-domain
    - http://spor.ema.europa.eu/v1/lists/100000073343 # ema-shelf-life-type
    - http://spor.ema.europa.eu/v1/lists/200000003186 # ema-intended-effect
    